Validate inputs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -41,12 +41,12 @@ jobs:
     name: validate inputs
     id: validate_inputs
     steps:
-      name: validations
-      run: |
-        if [ -z ${{ inputs.parent_version }} ]; then
-          echo "The input 'parent_version' cannot be null or empty"
-          exit 1
-        fi
+      - name: validations
+        run: |
+          if [ -z ${{ inputs.parent_version }} ]; then
+            echo "The input 'parent_version' cannot be null or empty"
+            exit 1
+          fi
 
   release_prepare: # prepare for a release in scm, creates the tag and release branch with the proper release versions
     name: Call release prepare
