Validate inputs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,8 +31,18 @@ env:
   GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
 
 jobs:
+  validate_inputs:
+    name: validate inputs
+    id: validate_inputs
+    run: |
+      if [ -z ${{ inputs.parent_version }} ]; then
+        echo "The input 'parent_version' cannot be null or empty"
+        exit 1
+      fi
   release_prepare: # prepare for a release in scm, creates the tag and release branch with the proper release versions
     name: Call release prepare
+    needs: validate_inputs
+    if: ${{ jobs.validate_inputs.result }} == 'success'
     # uses: ./.github/workflows/release-prepare.yml # same repository
     uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-prepare.yml@issue/812-action-release-prepare-workflow
     with:
